### ISSUE TITLE
SoundAPI.releaseInfo error: url.replace is not a function

### ISSUE THREAD

**Issue by gavinbains** [soundxyz/sdk#181]
Getting the following stack trace when trying to call:
```typescript
import { SoundClient } from "@soundxyz/sdk"
import { SoundAPI } from "@soundxyz/sdk/api"

const soundAPI = SoundAPI({
    apiKey: process.env.SOUNDXYZ_API_KEY,
})
SoundClient({ provider, soundAPI }).soundAPI.releaseInfo({ contractAddress }))
```

I know i'm using a contract address because i've pulled it from the [subgraph](https://api.thegraph.com/subgraphs/name/soundxyz/sdk-production/graphql?query=query+Songs+%7B%0A++songs+%7B%0A++++id%0A++++address%0A++++owner%0A++++fundingRecipient%0A++++minters+%7B%0A++++++id%0A++++++address%0A++++++price%0A++++%7D%0A++%7D%0A%7D%0A%0Aquery+Minters+%7B%0A++minters+%7B%0A++++address%0A++++id%0A++++edition+%7B%0A++++++address%0A++++++owner%0A++++%7D%0A++%7D%0A%7D%0A%0Aquery+Minter%28%24minterId%3A+String%29+%7B%0A++minter%28id%3A+%24minterId%29+%7B%0A++++edition+%7B%0A++++++address%0A++++%7D%0A++%7D%0A%7D%0A%0Aquery+Song%28%24songId%3A+String%29+%7B%0A++song%28id%3A+%24songId%29+%7B%0A++%09address%0A++++minters+%7B%0A++++++id%0A++++++address%0A++++%7D%0A++%7D%0A%7D) 

```
TypeError: url.replace is not a function
    at /.../node_modules/isomorphic-unfetch/index.js:3:36
      at graphqlRequest (/.../node_modules/@soundxyz/sdk/api.js:27:12)
        at Object.releaseInfo (/.../node_modules/@soundxyz/sdk/api.js:58:14)
          at resolve (/.../server/src/schemas/soundxyz/index.ts:84:36)
            at field.resolve (/.../node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)
              at resolveField (/.../node_modules/graphql/execution/execute.js:464:18)
                at executeFields (/.../node_modules/graphql/execution/execute.js:292:18)
                  at executeOperation (/.../node_modules/graphql/execution/execute.js:236:122)
                    at executeImpl (/.../node_modules/graphql/execution/execute.js:116:14)
                      at execute (/.../node_modules/graphql/execution/execute.js:60:35)
                        at execute (/.../node_modules/apollo-server-core/src/requestPipeline.ts:497:34)
                          at processGraphQLRequest (/.../node_modules/apollo-server-core/src/requestPipeline.ts:387:28)
                            at runMicrotasks (<anonymous>)
                              at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                at processHTTPRequest (/.../node_modules/apollo-server-core/src/runHttpQuery.ts:346:24)
```

**Comment by saihaj** [comment]
Can you share a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_working_example). You can either use [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or a public GitHub repo.

**Comment by vigneshka** [comment]
Hey @gavinbains , can you share the contractAddress?

**Comment by gavinbains** [comment]
> Hey @gavinbains , can you also share the contractAddress?

`0x003d03980d2d4332e5f92e54905a694c614df36f`

this is the contractAddress i'm using to test, i pulled it by calling the `Songs` query on: https://api.thegraph.com/subgraphs/name/soundxyz/sdk-production/graphql

**Comment by gavinbains** [comment]
> Can you share a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_working_example). You can either use [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or a public GitHub repo.

this is difficult to do since i would have to create a provider, can the sdk work if only the SoundAPI is passed in for the purposes of hosting on code sandbox?

**Comment by saihaj** [comment]
> This is difficult to do since i would have to make a provider -- can the sdk work with just the SoundAPI?

right now it will use the SoundAPI. We don't have the subgraph integration merged in yet. https://github.com/soundxyz/sdk/pull/129

**Comment by saihaj** [comment]
> 0x003d03980d2d4332e5f92e54905a694c614df36f

it is this release that I get back when I query our API https://www.sound.xyz/grady/jon-and-vinnys-ft-lackhoney

**Comment by gavinbains** [comment]
> > 0x003d03980d2d4332e5f92e54905a694c614df36f
> 
> it is this release that I get back when I query our API https://www.sound.xyz/grady/jon-and-vinnys-ft-lackhoney

How are you querying your api? is it through the sdk or through the graphiql interface? I can't get a non-error response from the sdk.

i either get the above error, or i get `Address must be a sound edition contract`

**Comment by gavinbains** [comment]
> > This is difficult to do since i would have to make a provider -- can the sdk work with just the SoundAPI?
> 
> right now it will use the SoundAPI. We don't have the subgraph integration merged in yet. #129

what is the difference between
```
SoundClient({ provider, soundAPI })
// and 
SoundClient({ soundAPI })
```

will the latter work?

**Comment by saihaj** [comment]
> How are you querying your api? is it through the sdk or through the graphiql interface? I can't get a non-error response from the sdk.

I used our GraphiQL to make request. Our API does require you to have an API key.

> what is the difference between
> 
> ```ts
> SoundClient({ provider, soundAPI })
> // and 
> SoundClient({ soundAPI })
> ```

`provider` is an instance of `ethers` whereas `soundAPI` is just an instance that helps setup creds for the SoundAPI.

**Comment by gavinbains** [comment]
what functions would i need to call on either the API or the SDK to mint editions/releases? whats the difference between an edition and a release?

**Comment by gavinbains** [comment]
> > How are you querying your api? is it through the sdk or through the graphiql interface? I can't get a non-error response from the sdk.
> 
> I used our GraphiQL to make request. Our API does require you to have an API key.
> 
> > what is the difference between
> > ```ts
> > SoundClient({ provider, soundAPI })
> > // and 
> > SoundClient({ soundAPI })
> > ```
> 
> `provider` is an instance of `ethers` whereas `soundAPI` is just an instance that helps setup creds for the SoundAPI.

so in this case, we MUST declare the instance of SoundClient with BOTH a provider and the api key, right?

**Comment by gigamesh** [comment]
> what functions would i need to call on either the API or the SDK to mint editions/releases? whats the difference between an edition and a release?

Editions and releases refer to roughly the same thing abstractly, but edition is what its called on-chain and release is what its called in our database/api. 

Here are the [protocol docs](https://docs.sound.xyz/protocol/core/sound-edition#mint) on minting, but the easiest way is to [use the SDK](https://docs.sound.xyz/sdk/write#mint). 

The API is only for interacting with sound.xyz data. All the core protocol functionality (like minting) can be utilized without our API. :D

**Comment by saihaj** [comment]
the `id` to subgraph is case sensitive. So you need to lower case `0x87DB620e0bD6Ca95F25CbEafd45ad3D2e267447F` this address then you can do a lookup.
