### ISSUE TITLE
Attempted import error: SoundEditionV1_1__factory is not exported

### ISSUE THREAD

**Issue by olivermontes** [soundxyz/sdk#205]
### Error trace

- npm run build

````
Failed to compile.

Import trace for requested module:
./node_modules/@soundxyz/sdk/client.mjs
./node_modules/@soundxyz/sdk/index.mjs

./node_modules/@soundxyz/sdk/client.mjs
Attempted import error: 'SoundEditionV1_1__factory' is not exported from '@soundxyz/sound-protocol/typechain/index' (imported as 'SoundEditionV1_1__factory').

> Build failed because of webpack errors
````

### Debug

- The current class exported from '@soundxyz/sound-protocol/typechain/index'  is "ISoundEditionV1_1__factory" not "SoundEditionV1_1__factory"

### Version packages

- "@soundxyz/sdk": "^0.14.1",
- "@soundxyz/sound-protocol": "^1.4.0",

**Comment by olivermontes** [comment]
go back prev version sound-protocol work

`````
  "overrides": {
    "@soundxyz/sound-protocol": "1.3.0"
  }
``````

continue to explore good solution

**Comment by PabloSzx** [comment]
that version of SDK is outdated, we already released v1

**Comment by PabloSzx** [comment]
This was just an issue with sdk version mismatching the expected sound protocol version, 2 weeks ago we released sdk v1 which will be louder with compatible sound-protocol versions on the peer dependencies 

https://github.com/soundxyz/sdk/releases

sorry for the issues pre-v1 of SDK had
