### ISSUE TITLE
Can you expand on the thoughts behind pull-env?

### ISSUE THREAD

**Issue by motdotla** [soundxyz/sdk#262]
Hey @PabloSzx, I saw this:

https://github.com/soundxyz/sdk/blob/7427d30718cb671ca2e620dca58a9696a374c97d/example/pull-env.mjs

Thought it was cool and clever.

Could you expand on how your users are using it? Maybe we can provide an even more convenient way to do this for other orgs publishing opensource like Sound.

For example, I think of how many open source devs use a `.env.example` which the user of their software copies to their .env file.

**Comment by PabloSzx** [comment]
Hey, the motivation behind that script was being able to pull the latest state of the environment variables without relying on the developer to be on UNIX / have curl downloaded, and not having the env variables directly in the repo either
